version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint:
      - "npm"
    command: ["start"]
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}
      - PANOPTES_API_APPLICATION=${PANOPTES_API_APPLICATION}
      - PANOPTES_API_HOST=${PANOPTES_API_HOST}
    volumes:
      - ${PWD}:/src
      - /src/node_modules