name: Run Pandora Tests

on:
    # Run this workflow on creation (or sync to source branch) of a new pull request
    pull_request:

    # Allow running this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Node.js build
      id: build
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm ci
    - run: npm run test
    - run: npm run build
