name: Run Pandora Tests

on:
    # Run this workflow on creation (or sync to source branch) of a new pull request
    pull_request:

    # Allow running this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Node.js build
      id: build
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm run test
